### ISSUE TITLE
Injectors should not stop injecting when first injector returns true

### ISSUE THREAD

**Issue by vanta** [marcingrzejszczak/spock-subjects-collaborators-extension#14]
In following scenario, I have 2 Java classes `A` and `B` and want collaborators defined in `A` and  `B` to be injected. Unfortunately, when setter is found, property injector is not invoked. 

If you don't have control over base class and you don't want to have setters in your class, you're stuck. Following test fails but should pass I believe.

How about invoking all injectors, checking if collaborator is null and if so trying to inject value?

```groovy
public abstract class A {
    Integer a;
    public void setA(Integer a){
        this.a = a;
    }
    public Integer getA() {
        return a;
    }
}

public class B extends A {
    String b; // no setter
}

class B_Test extends Specification {

    @Collaborator
    Integer a = 1
    @Collaborator
    String b = "22"

    @Subject
    B underTest

    def "should inject collaborators"() {
        expect:
        underTest.a == a
        underTest.b == b
    }
}

```

**Comment by marcingrzejszczak** [comment]
Hmm come to think of it makes sense... Do you want to do a PR? ;)

**Comment by vanta** [comment]
I can, but no idea when. And I suck in Groovy :D

**Comment by marcingrzejszczak** [comment]
@vanta - check this out https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/pull/15 . Is it what you wanted? You can build locally and apply 1.2.0-SNAPSHOT extension version to check it out

**Comment by vanta** [comment]
@marcingrzejszczak Thanks, will check and let you know

**Comment by marcingrzejszczak** [comment]
@vanta ping?

**Comment by vanta** [comment]
@marcingrzejszczak I was pretty busy, will check it this week. I looked at the code at looks promising ;)

**Comment by vanta** [comment]
@marcingrzejszczak works like a charm, thank you.
