### ISSUE TITLE
Collaborators from inherited class are not injected

### ISSUE THREAD

**Issue by vanta** [marcingrzejszczak/spock-subjects-collaborators-extension#18]
When Collaborators are present in parent class and Subject in the class that inherits from it, they are not injected. This is because of method in class `SubjectsCollaboratorsUtils`:
```
    public static Collection<Field> findAllDeclaredFieldsWithAnnotation(Object object, Class... annotatedClasses) {
        return object.class.declaredFields.findAll { Field field ->
            annotatedClasses.any { Class annotatedClass ->
                return annotatedClass in field.declaredAnnotations*.annotationType()
            }
        }
    }
```
`declaredFields` property returns only fields from class itself, without inherited ones.

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/issues/19
