### ISSUE TITLE
Enhancement : initialized fields should not be excluded from the matching process.

### ISSUE THREAD

**Issue by ta7tou7** [marcingrzejszczak/spock-subjects-collaborators-extension#20]
When I upgraded my version from _1.1.0_ to _1.2.2_ some of my tests were be broken.
it was caused by a behavior change : for _1.2.2_ when an object is already initialized it will  be excluded immediately from the matching process.
But most of time when I declare a field in Specification with Collaborate annotation and the same type and name that another field from the subject class, I expect that it will be injected in this subject field regardless of his initialization state.

**My suggestion is the following** : 
-When two fields match with name and type then specification field will be injected in the subject field
-When one fields from specification matches by type one or more fields from subject then remove initialized field and keep only non-initialized ones.

You find below a specification class that illustrate my expected behavior :

```
class PropertiesInjectionWithCollaborators extends Specification
{
    @Collaborator
    SomeOtherClass someOtherClass = Mock()
    @Subject
    SomeClass someClass

    def 'someMethod should be called from the collaborator object' ()
    {
        given:
        someOtherClass.someMethod() >> "collaborator method"
        when :
        String result = someClass.someOtherClass .someMethod()
        then :
        result.equals("collaborator method")
    }
}
    class SomeClass
    {
        SomeOtherClass someOtherClass = new SomeOtherClass()
    }
    class SomeOtherClass
    {
        String someMethod()
        {
            "real method"
        }
    }
```

**Comment by marcingrzejszczak** [comment]
I've just executed this and it's working exactly as you wanted. So what exactly would you want to happen for the presented scenario?

**Comment by marcingrzejszczak** [comment]
Here is the PR https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/pull/21 - the build is passing.

**Comment by ta7tou7** [comment]
my bad, sorry for this !
I forgot to remove the someClass constructor.
I remove it now :) 
Could you please execute this test again ?

**Comment by marcingrzejszczak** [comment]
Wait a second... You'd like to inject a mock to an initialized field?? I mean you'd like 

```
class SomeClass
    {
        SomeOtherClass someOtherClass = new SomeOtherClass()
    }
```

to have the `someOtherClass` uninitialized and a mock set there?

**Comment by marcingrzejszczak** [comment]
This is a terrible, terrible idea! Why would you even want this to happen? It's a violation of every existing rules of good coding. I mean the very field injection is a bad idea, but why do you want to inject to an initialized field? Please jut create a constructor and inject things properly. WDYT about this?

**Comment by ta7tou7** [comment]
it was the case in 1.1.0 !
and when you have a lot of legacy code believe me it's not an easy trick to do it !

In the other side when I tag a specification field with Collaborator and I give it the same name and type than an other field in the subject class I found it logic that those two fields match and that injection performed regardless of whether the field is initialized or not (someOtherClass in this case).
To me if a tester meet all those requirements(Collaborator annotation, same type and name) it's obvious that he wants to inject the mock into the subject field whether it's already initialized or not.

For other cases where only type match for example, it could be tricky then to exclude initialized fields,
but here  when both name and type match and furthermore the field is annotated with Collaborator it doesn't make sense IMHO to exclude the only possible candidate for matching
