### ISSUE TITLE
Spock 2.0

### ISSUE THREAD

**Issue by Raniz85** [marcingrzejszczak/spock-subjects-collaborators-extension#26]
The code works as-is with Spock 2.0, though it pulls in old version of Groovy and Spock through dependencies.

Would be nice with a new release that depends on Spock 2.0 and Groovy 3.0.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/commit/b4e06be79d4dd66f749114354d56836322a62467
