### ISSUE TITLE
Inject field into class with private constructor

### ISSUE THREAD

**Issue by FlorianLautenschlager** [marcingrzejszczak/spock-subjects-collaborators-extension#4]
Hey there,

i want to inject the server object into my singleton SolrRemoteConnection object. But 

```
   @Collaborator
    SolrServer server = Mock(SolrServer.class)

    @Subject
    SolrRemoteConnection connection = SolrRemoteConnection.getInstance("http://localhost:8983/solr")
```

I get the following exception:

```
java.lang.NullPointerException
	at com.blogspot.toomuchcoding.spock.subjcollabs.NonConstructorBasedInjector.instantiateSubjectAndSetOnSpecification(NonConstructorBasedInjector.groovy:19)
```

and I think the failure is placed in the class NonConstructorBasedInjector at the following line:
```
Constructor constructorWithMinArgs = fieldInfo.type.constructors.min(CONSTRUCTOR_SIZE_COMPARATOR)
```
Perhaps it's enough to change it to this line:
```
Constructor constructorWithMinArgs = fieldInfo.type.declaredConstructors.min(CONSTRUCTOR_SIZE_COMPARATOR)
```

Cheers

**Comment by marcingrzejszczak** [comment]
Hi!

Could you please show me part of the SolrRemoteConnection so that I can create a test for regression purposes? Or you can paste some piece of code that resembles this class.

**Comment by FlorianLautenschlager** [comment]
You are right. My SolrRemoteConnection has some additional features and i want to test them. For that i have to mock the internal SolrServer object. Addintionally my SolrRemoteConnection is a singleton due to some reasons.

I want a unit test that looks like this (works for a public constructor):
```
   @Collaborator
    SolrServer server = Mock(SolrServer.class)

    @Subject
    SolrRemoteConnection connection = SolrRemoteConnection.getInstance("http://localhost:8983/solr")

    def "test ping server correct and error"() {
        when:
        def pingResponse = Mock(SolrPingResponse.class)
        pingResponse.getStatus() >>> status
        server.ping() >>> pingResponse

        then:
        connection.pingServer() == result

        where:
        status << [0, 1]
        result << [true, false]
    }
```

**Comment by marcingrzejszczak** [comment]
I think that it's impossible to do that using my tool and I think that here the biggest problem actually is your design. I know that this extension is supposed to allow a lot of hacks when the design is wrong but IMO what you're trying to achieve is not possible with spock-subjects-collaborators-extension. It was designed to allow instantiation and injection at the same time.

But you can use Groovy magic to inject this server there. In the given section of the test you can explicitly inject the server to a field (http://refaktor.blogspot.com/2012/07/private-fields-and-methods-are-not.html)

**Comment by FlorianLautenschlager** [comment]
So what would be a correct design in your opinon? I do not think that my design is the problem. It's only a singleton to avoid duplication connections. And i do not want to create an integration test for testing my connection wrapper code.

**Comment by marcingrzejszczak** [comment]
If this is a unit test then you could have a package scoped method

```
static SolrRemoteConnection getInstance(String connection, SolrServer server)
```

or even better - create a package scope constructor that you will be able to address in tests.

**Comment by FlorianLautenschlager** [comment]
But with this design decision, the creator have to know the SolrServer - anyway. The only thing i want to say is that your tool can not inject fields if the constructor is private.

**Comment by marcingrzejszczak** [comment]
Sure I'll try to fix that you can actually inject via private constructors but the example you've shown will not work cause you've already instantiated the object. I'll try to release it tomorrow.

As for the design - SolrServer is a dependency of your class thus it should be injectable. To make the concept understandable for others you can add the @VisibleForTesting on the static method / constructor

```
@VisibleForTesting
static SolrRemoteConnection getInstance(String connection, SolrServer server)
```

**Comment by marcingrzejszczak** [comment]
Try to use the latest 1.0.2 version - now you should be able to inject collaborators into subject with private constructor. Still IMO the design is wrong but you'll do of course as you wish. Once you confirm that it's working I'll close the issue.

**Comment by marcingrzejszczak** [comment]
Hi! Maybe with 1.1.0 release the extension would actually inject collaborators to your object. Check it out if you still need this :)
