### ISSUE TITLE
Requires Java 8 runtime?

### ISSUE THREAD

**Issue by michaelbannister** [marcingrzejszczak/spock-subjects-collaborators-extension#5]
Hi,
I'm trying to use this with Spock 1.0 but I can only use Java 6 and when I run a spec using your extension I get:
`java.lang.UnsupportedClassVersionError: com/blogspot/toomuchcoding/spock/subjcollabs/Collaborator : Unsupported major.minor version 52.0`

I can see in your Travis file you test/build this under JDK 6, 7, 8 but it seems the version you've published to Bintray isn't targeting version 1.6.
Any chance you could add `sourceCompatibility = 1.6` to your gradle file?

Thanks! :)

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/commit/0afa56ed21d4fd1167c2aec5f6278545ca23f954. Please download 1.0.3 and check if it's ok now. Then I'll close the ticket.

**Comment by michaelbannister** [comment]
Thank you – it's compiling just fine now!
(I'm still having other issues with collaborators not being injected, but I'll fiddle around a bit more to see if I'm missing something obvious.)

**Comment by marcingrzejszczak** [comment]
You're welcome. If it's my fault - just file an issue. If not then we can meet at Gitter and have a chat - https://gitter.im/marcingrzejszczak/spock-subjects-collaborators-extension
