### ISSUE TITLE
Spock Subjects-Collaborators extension not happy with stubbed method on Spy subject

### ISSUE THREAD

**Issue by marcingrzejszczak** [marcingrzejszczak/spock-subjects-collaborators-extension#8]
By @michaelbannister

Hi Marcin, thanks again for the fast response on the Java 6 compatibility issue.
I've identified the further problem I was having. My test involves a @Subject which is a Spy, and I stub a method which is called internally which would otherwise throw an exception (when run out-of-container). When the subject is managed by your extension, the stubbing is ignored, the original method is invoked and I get an exception.
 
I have created a failing spec which demonstrates this: https://gist.github.com/michaelbannister/afce6c6a5ad22649ffea

I'd be very grateful for any thoughts on why this is and whether the extension can be modified to allow stubbing/partial-mocking on a Spy, or whether the way it works is just not compatible.
Thanks!

**Comment by michaelbannister** [comment]
Fantastic! Thank you so much :) :+1:
